basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.pause(100)
    basic.showIcon(IconNames.Diamond)
    basic.pause(100)
    basic.showIcon(IconNames.House)
    basic.pause(100)
    basic.showIcon(IconNames.Confused)
    basic.pause(100)
})
